/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
    "Bose Soundtouch adapter settings": {             "en": "Bose Soundtouch adapter settings",                 "de": "Bose Soundtouch Adapter Einstellungen",            "ru": "Настройки адаптера Bose Soundtouch",               "pt": "Configurações do adaptador Bose Soundtouch",       "nl": "Instellingen Bose Soundtouch-adapter",             "fr": "Paramètres de l'adaptateur Bose Soundtouch",       "it": "Impostazioni dell'adattatore Bose Soundtouch",     "es": "Configuración del adaptador Bose Soundtouch",      "pl": "Ustawienia adaptera Bose Soundtouch",              "uk": "",                                                 "zh-cn": "Bose Soundtouch 适配器设置"},
    "address": {                                      "en": "IP address",                                       "de": "IP-Adresse",                                       "ru": "айпи адрес",                                       "pt": "endereço de IP",                                   "nl": "IP adres",                                         "fr": "adresse IP",                                       "it": "indirizzo IP",                                     "es": "dirección IP",                                     "pl": "adres IP",                                         "uk": "",                                                 "zh-cn": "IP地址"},
    "on save adapter restarts with new config immediately": {"en": "Once the settings are saved, the adapter will be restarted immediately.", "de": "Beim Speichern von Einstellungen wird der Adapter sofort neu gestartet.", "ru": "После сохранения настроек адаптер будет немедленно перезапущен.", "pt": "Assim que as configurações forem salvas, o adaptador será reiniciado imediatamente.", "nl": "Nadat de instellingen zijn opgeslagen, wordt de adapter onmiddellijk opnieuw opgestart.", "fr": "Une fois les paramètres enregistrés, l'adaptateur sera redémarré immédiatement.", "it": "Una volta salvate le impostazioni, l'adattatore verrà riavviato immediatamente.", "es": "Una vez guardada la configuración, el adaptador se reiniciará inmediatamente.", "pl": "Po zapisaniu ustawień adapter zostanie natychmiast ponownie uruchomiony.", "uk": "",                                                 "zh-cn": "保存设置后，适配器将立即重新启动。"},
};